### ISSUE TITLE
PID File is supposed to be deleted on heiko stop.

### ISSUE THREAD

**Issue by psiayn** [psiayn/heiko#1]
PID File generated in daemon mode is supposed to be deleted via the `context.Release()` call. As of right now, any form of interrupt ( SIGTERM / SIGINT ) doesn't seem to change it's behaviour. 

Also go-daemon seems to be pretty old, could that be the issue?

**Comment by MadhavJivrajani** [comment]
imo the reason that the PID files don't get deleted is that in the code, `context.Release()` is `defer`ed, and `defer` isn't run if signals like `SIGTERM` and `SIGINT` are sent to the process because the process itself is basically stopped. You can try running [this](https://play.golang.org/p/YM9RayvB8HN) snippet and sending different signals to it.

This behaviour can be changed by adding some form of signal handling, like [here](https://github.com/sevlyar/go-daemon/blob/master/examples/cmd/gd-signal-handling/signal-handling.go). This works pretty well.

**Comment by Samyak2** [comment]
> imo the reason that the PID files don't get deleted is that in the code, `context.Release()` is `defer`ed, and `defer` isn't run if signals like `SIGTERM` and `SIGINT` are sent to the process because the process itself is basically stopped. You can try running [this](https://play.golang.org/p/YM9RayvB8HN) snippet and sending different signals to it.

Ah that explains it. The example helped me see it in action, the defer statement isn't run on any of SIGINT, SIGHUP or SIGTERM. Thanks for that!


> This behaviour can be changed by adding some form of signal handling, like [here](https://github.com/sevlyar/go-daemon/blob/master/examples/cmd/gd-signal-handling/signal-handling.go). This works pretty well.

We had explored this before, but we weren't sure of how to pass the flags from cobra/viper. `go-daemon` seems to use the `flag` package along with their own interface for specific flags. Do you know of a way to convert viper flags to the flags required by `go-daemon`?

My initial idea was to pass a pointer to [`daemon.BoolFlag`](https://github.com/sevlyar/go-daemon/blob/63a89ce7b9a81c5f9fa5f6fe14fedb02538a072c/command.go#L25) using the value from viper, but that seems like a hack.
